export const GET_ME_DATA_PENDING = "GET_ME_DATA_PENDING";
export const GET_ME_DATA_SUCCESS = "GET_ME_DATA_SUCCESS";
export const GET_ME_DATA_FAILED = "GET_ME_DATA_FAILED";

export const GET_USER_PENDING = "GET_USER_PENDING";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAILED = "GET_USER_FAILED";

export const LOGIN_PENDING = "LOGIN_PENDING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const UPDATE_ACCOUNT_PENDING = "UPDATE_ACCOUNT_PENDING";
export const UPDATE_ACCOUNT_SUCCESS = "UPDATE_ACCOUNT_SUCCESS";
export const UPDATE_ACCOUNT_FAILED = "UPDATE_ACCOUNT_FAILED";

export const REGISTRATION_PENDING = "REGISTRATION_PENDING";
export const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS";
export const REGISTRATION_FAILED = "REGISTRATION_FAILED";

export const LOGOUT = "LOGOUT";
